plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.casey'
version = '0.0.1-SNAPSHOT'
description = 'ApplyFlow'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // JPA
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
    implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Database migrations
    implementation 'org.springframework.boot:spring-boot-flyway'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    // BCrypt encoding & JWT
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'com.nimbusds:nimbus-jose-jwt:9.37.3'

    // Email verification
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // Dotenv for .env file loading
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'

    // Rate limiting
    implementation("com.bucket4j:bucket4j-core:8.7.0")
}

tasks.named('test') {
    useJUnitPlatform()
}
