spring.application.name=ApplyFlow

# RSA Key Confiurration for JWT
rsa.prviate-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/private.pem

# JWT Settings

# 1hr expiry
jwt.expiration-ms=3600000