spring.application.name=ApplyFlow

# RSA Key Configuration for JWT
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem

# JWT Settings
# 1hr expiry
jwt.expiration-ms=3600000


# Gmail SMTP Connection
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=caseydevs5@gmail.com
spring.mail.password=fquo bmpb stfx ywnj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true