spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

rsa.private-key=file:/run/secrets/jwt-private.pem
rsa.public-key=file:/run/secrets/jwt-public.pem

app.security.cookie-secure=true
app.security.cookie-same-site=Lax
app.security.allow-h2-console=false
